"""empty message

Revision ID: d2be04b1e2fd
Revises: 7d97635601ec
Create Date: 2021-04-26 15:17:29.906355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2be04b1e2fd'
down_revision = '7d97635601ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_likes_comment_id_fkey', 'comment_likes', type_='foreignkey')
    op.create_foreign_key(None, 'comment_likes', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment_likes', type_='foreignkey')
    op.create_foreign_key('comment_likes_comment_id_fkey', 'comment_likes', 'posts', ['comment_id'], ['id'])
    # ### end Alembic commands ###
